### PR TITLE
Update api.md

### PR DESCRIPTION
**Pull request by sunitaprakash**
Remove the stop command for session from the docs.

# What does this PR do?
Remove the stop command for session from the docs 
DOC-264

Explain purpose of PR and any useful context.

### CODE REVIEW

**Comment by oojo12** [comment]
The content is fine but next time please follow our docs PR process. @essiequoi this actually rectifies the documentation update required for https://linear.app/gridai/issue/GRID-8528/grid-stop-session-deletes-the-session-instead-just-stopping-it

**Review by essiequoi — APPROVED** [review]
looks good.

**Comment by essiequoi** [comment]
@pritamsoni-hsr these changes will get overwritten the next time the build and deploy action runs, right? 

@sunitaprakash @oojo12 in the future, please also open a PR against the [Grid monorepo ](https://github.com/gridai/grid/tree/master/grid-cli/grid/cli/cli) so the command is removed from the CLI as well. I'll do it this time, but let me know if you want me to show you how.  

Thanks!

**Comment by essiequoi** [comment]
looks like @oojo12 already made the PR against grid CLI :) 🚀

**Pull request merged**
