### PR TITLE
fix folder navigation paths

### PR DESCRIPTION
**Pull request by rasbt**
# What does this PR do?

There are two little fixes correcting the folder paths. 

For the 2nd correction, where we originally had

    python flash-image-classifier.py  --data_dir ../cifar5 --gpus 2 --epochs 4

I think either

    python flash-image-classifier.py  --data_dir ~/datastores/cifar5 --gpus 2 --epochs 4

or

    python flash-image-classifier.py  --data_dir ../../datastores/cifar5 --gpus 2 --epochs 4

would work.

### CODE REVIEW

**Comment by essiequoi** [comment]
@oojo12 this would need to be applied to dev as well

**Comment by oojo12** [comment]
@rasbt please confirm it works and then @ me. Also just make this PR into dev. Additionally, for this to work you need to:

1. if running from a session have created the session with the datastore attached
2. add the cifar data to the publicly available repo so the path is always correct for local runs

@essiequoi I am going to add you as a reviewer as I am not sure why the docs have you run tutorials from the session as opposed to your local machine. Please decide on a format for this tutorial so the appropriate changes can be made.

**Comment by oojo12** [comment]
took a look at the docs again @rasbt based on following the docs all the way through this command would work for

`python flash-image-classifier.py  --data_dir ~/datastores/cifar5 --gpus 2 --epochs 4`

**Comment by oojo12** [comment]
made the change for you to that in case users place clone to a different folder

**Review by oojo12 — APPROVED** [review]

**Comment by oojo12** [comment]
@essiequoi approving and merging. As you, JP, and I may have a meeting to decide if we want to have users follow this tutorial via a session or from their local machine

**Comment by rasbt** [comment]
Ok I see you just did ;) 👌

**Pull request merged**
