### PR TITLE
fix sidebar SAL-435

### PR DESCRIPTION
**Pull request by pritamsoni-hsr**
# What does this PR do?

use autogenerated sidebar

### CODE REVIEW

**Comment by oojo12** [comment]
Looks like it fulfills the intention to me. I will update the ordering of the BYOC page content

@essiequoi any ideas on better product names for "Grid managed" and "Customer managed" BYOC mode? I think we can better communicate the advantages + intentions of both features via naming. Additionally, the grid-cluster-context page seems like it might be out of place and should be subsumed in the individual BYOC pages, thoughts?

**Comment by oojo12** [comment]
We also need to change the order for Runs, Sessions, and Billing so it reads like a nice story for the sidebar and guides users appropriately. Additionally, datastores has a sidebar option simply named Create this should be fixed. @essiequoi you want to tackle all this here or in separate PR's?

**Comment by oojo12** [comment]
@pritamsoni-hsr can you organize the platform sidebar alphabetically? Additionally, can you provide instruction to team to maintain the nested sidebar with ordering? It seems that when there is a folder we get the nested sidebar but applying the prescribed ordering solution there does not effect the content in the desired fashion. After that @essiequoi will be able to quickly review when she has availability and merge. Thank you.

**Comment by oojo12** [comment]
It would be nice to have the same request above applied to the runs page so that yaml_configs is directly before FAQ.

**Comment by oojo12** [comment]
@essiequoi Product will have to prioritize this as it is something that is not within my authority even in the sales-eng collab.

**Comment by pritamsoni-hsr** [comment]
@oojo12 I think it is alphabetic already.

**Comment by oojo12** [comment]
Did you build locally and check?

**Comment by pritamsoni-hsr** [comment]
yeah

**Comment by oojo12** [comment]
@pritamsoni-hsr please sort the folders and files under the platform folder alphabetically. The folders should not be at the bottom. Similarly the Runs page please move the yaml_config folder to be directly above the FAQ page and resolve the merge conflicts.

**Review by oojo12 — APPROVED** [review]

**Comment by oojo12** [comment]
@essiequoi merge if this is good to you.

**Comment by essiequoi** [comment]
@oojo12 @pritamsoni-hsr this can't be merged due to conflicts listed above

**Review by essiequoi — APPROVED** [review]

**Pull request merged**
